In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

print(A)
print("dtype of matrix A: ", A.dtype)

[[1 2]
 [3 4]]
dtype of matrix A:  int64


In [2]:
B = np.array([[1, 2],
              [3, 4]], dtype=np.float32)

print(B)
print("dtype of matrix B: ", B.dtype)

[[1. 2.]
 [3. 4.]]
dtype of matrix B:  float32


In [3]:
# Lưu ý phải gán A = A.astype() để lưu thay đổi cho A
A = A.astype(np.float32)
print(A.dtype)

float32


In [4]:
R = np.random.randn(2, 3)
print(R)

[[ 1.28810374 -0.79238614 -0.32776005]
 [-0.62510102  0.39891493 -1.39576126]]


In [5]:
R = np.random.normal(loc=1, scale=2, size=(2, 3))
print(R)

[[ 1.75032976  3.2426828   2.52541944]
 [-3.66904972  4.41984353  1.39445278]]


In [6]:
R = np.random.uniform(low=-1, high=1, size=(2, 3))
print(R)

[[ 0.58330912  0.0827924  -0.59443436]
 [ 0.7381164   0.5265381   0.66430905]]


In [7]:
R = np.random.randint(low=-5, high=5, size=(2, 3))
print(R)

[[2 3 1]
 [1 1 0]]


In [8]:
# from google.colab import drive
# import os

# Mount google driver
# drive.mount('/content/drive/')
# os.chdir("drive/My Drive/mybook")

import numpy as np

# Khởi tạo một mảng ngẫu nhiên A
A = np.random.randn(3, 3)
A

array([[-0.12101232, -3.94410163,  0.34558961],
       [-0.40323939,  0.87749475,  1.08300805],
       [ 3.59616781, -1.62671951, -0.562392  ]])

In [9]:
# Định dạng npy
np.save('numpy_save/A', A)
# Định dạng txt
np.savetxt('numpy_save/A.txt', A)
# List các file
!ls -a numpy_save

.  ..  A.npy  A.txt


In [10]:
A = np.load("numpy_save/A.npy")
print(A)

[[-0.12101232 -3.94410163  0.34558961]
 [-0.40323939  0.87749475  1.08300805]
 [ 3.59616781 -1.62671951 -0.562392  ]]


In [11]:
np.loadtxt("numpy_save/A.txt")
print(A)

[[-0.12101232 -3.94410163  0.34558961]
 [-0.40323939  0.87749475  1.08300805]
 [ 3.59616781 -1.62671951 -0.562392  ]]


In [12]:
import pandas as pd

df = pd.read_csv("numpy_save/A.txt", header=None, sep=" ")
df

0         1         2
0 -0.121012 -3.944102  0.345590
1 -0.403239  0.877495  1.083008
2  3.596168 -1.626720 -0.562392

In [13]:
A = df.values
print(A)

[[-0.12101232 -3.94410163  0.34558961]
 [-0.40323939  0.87749475  1.08300805]
 [ 3.59616781 -1.62671951 -0.562392  ]]


In [14]:
import numpy as np 
X = np.array([[1, 2, 3, 4],
              [4, 5, 6, 2],
              [7, 8, 9, 1],
              [2, 5, 1, 5]])

In [15]:
# Truy cập vào phần tử thuộc dòng 1 và cột 2
print(X[1, 2])

6


In [16]:
# Truy cập vào các dòng từ 1 đến 2 và các cột từ 1 đến 2
print(X[1:3, 1:3])

[[5 6]
 [8 9]]


In [17]:
# Truy cập vào 2 dòng, 2 cột đầu tiên
print(X[:2, :2])

[[1 2]
 [4 5]]


In [18]:
# Truy cập vào 2 dòng, 2 cột cuối cùng
print(X[-2:, -2:])

[[9 1]
 [1 5]]


In [19]:
# Truy cập vào dòng 0 và 2. Cách lấy indices không liên tục.
print(X[[0, 2], :])

[[1 2 3 4]
 [7 8 9 1]]


In [20]:
B = np.array(np.arange(12))
print("B: \n", B)
print("B.shape: ", B.shape)

B: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
B.shape:  (12,)


In [21]:
# dùng B.reshape()
B.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
# dùng np.reshape()
np.reshape(B, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
B.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
B = np.reshape(B, (2, -1))
print(B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [25]:
# Khởi một bức ảnh ngẫu nhiên có kích thước channels x width x height= 3 x 28 x 28
A = np.random.randint(0, 255, size=(3, 28, 28))
print("A.shape: ", A.shape)
# Chuyển channels về cuối
A = np.transpose(A, (1, 2, 0))
print("A transpose shape: ", A.shape)

A.shape:  (3, 28, 28)
A transpose shape:  (28, 28, 3)


In [26]:
A = np.random.randint(0, 255, size=(28, 28, 3))
B = np.random.randint(0, 255, size=(28, 28, 3))
print("A.shape:", A.shape)
print("B.shape:", B.shape)
AB = np.concatenate((A, B), axis=1)
print("shape after concatenate: ", AB.shape)

A.shape: (28, 28, 3)
B.shape: (28, 28, 3)
shape after concatenate:  (28, 56, 3)


In [27]:
np.stack([A, B]).shape

(2, 28, 28, 3)

In [28]:
# Stack theo chiều vertical
print(np.vstack([A, B]).shape)

# Stack theo chiều horizontal
print(np.hstack([A, B]).shape)

(56, 28, 3)
(28, 56, 3)


In [29]:
A = np.random.randint(0, 2, size=(1, 2, 3))
B = np.random.randint(0, 2, size=(1, 3))

# A.dot(B)

In [30]:
# Mở rộng mảng
B = np.expand_dims(B, axis=-1)
print("B new shape: ", B.shape)
print("A.dot(B) shape: ", A.dot(B).shape)

B new shape:  (1, 3, 1)
A.dot(B) shape:  (1, 2, 1, 1)


In [31]:
B = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10, 11]])

# Tìm ra phần tử nhỏ nhất của B
B.min()

0

In [32]:
# Tìm ra phần tử nhỏ nhất của B theo dòng
B.min(axis=1)

array([0, 6])

In [33]:
# Tìm ra phần tử nhỏ nhất của B theo cột
B.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [34]:
print(B.max(axis=1))
print(B.mean(axis=1))
print(B.sum(axis=1))

[ 5 11]
[2.5 8.5]
[15 51]


In [35]:
A = np.array([[1, 3, 6], 
              [2, 7, 9]])

B = np.array([[0, 4, 5], 
              [1, 6, 10]])

# Tìm các phần tử maximum của A và B ở cùng vị trí indice
np.maximum(A, B)

array([[ 1,  4,  6],
       [ 2,  7, 10]])

In [36]:
# Tìm các phần tử minimum của A và B ở cùng vị trí indice
np.minimum(A, B)

array([[0, 3, 5],
       [1, 6, 9]])

In [37]:
# Tìm ra indice có giá trị lớn nhất của véc tơ
A = np.array([1, 5, 3, 2, 4])
np.argmax(A)

1

In [38]:
# Tìm ra indice có giá trị lớn nhất của các dòng
A = np.array([[1, 2],
              [3, 4],
              [5, 0],
              [2, 1]])

np.argmax(A, axis=1)

array([1, 1, 0, 0])

In [39]:
B = np.array([[0.1, 0.2, 0.7],
              [0.6, 0.4, 0.0],
              [0.1, 0.5, 0.4],
              [0.3, 0.3, 0.4],
              [0.1, 0.8, 0.1]])

In [40]:
# Tìm ra indice của các cột theo thứ tự tăng dần
np.argsort(B, axis = 0)

array([[0, 0, 1],
       [2, 3, 4],
       [4, 1, 2],
       [3, 2, 3],
       [1, 4, 0]])

In [41]:
# Tìm ra indice của các dòng theo thứ tự tăng dần
np.argsort(B, axis = 1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]])

In [42]:
np.exp(B)

array([[1.10517092, 1.22140276, 2.01375271],
       [1.8221188 , 1.4918247 , 1.        ],
       [1.10517092, 1.64872127, 1.4918247 ],
       [1.34985881, 1.34985881, 1.4918247 ],
       [1.10517092, 2.22554093, 1.10517092]])

In [43]:
# Ma trận phân phối xác suất được tính dựa trên các dòng của ma trận B.
E = np.exp(B)
P = []

for i in range(E.shape[0]):
  Ei = E[i, :]
  pi = Ei/np.sum(Ei)
  P.append(pi)

P = np.array(P)
P

array([[0.25462853, 0.28140804, 0.46396343],
       [0.42237892, 0.34581461, 0.23180647],
       [0.26030255, 0.38832577, 0.35137169],
       [0.32204346, 0.32204346, 0.35591307],
       [0.2491434 , 0.5017132 , 0.2491434 ]])

In [44]:
# Tính max theo các dòng ta thu được véc tơ độ dài là rows
np.max(B, axis=1)

array([0.7, 0.6, 0.5, 0.4, 0.8])

In [45]:
np.max(B, axis=1, keepdims=True)

array([[0.7],
       [0.6],
       [0.5],
       [0.4],
       [0.8]])

In [46]:
import numpy as np
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [47]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [48]:
# Khởi tạo ma trận đơn vị với shape=5x5
I = np.identity(5, dtype=np.float16)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float16)

In [49]:
# Khởi tạo ma trận 1 với kích thước (3, 3)
A = np.ones((3, 3), dtype=np.float32)
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [50]:
# Khởi tạo ma trận B ngẫu nhiên kích thước (2, 3)
B = np.random.randn(2,3)
# Khởi tạo ma trân 1 có kích thước bằng với (2, 3)
A = np.ones_like(B)
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Khởi tạo ma trận 0 kích thước (3, 3)
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# Khởi tạo ma trận 0 có kích thước như ma trận B
np.zeros_like(B)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.diag(np.array([1, 2, 3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8 ,9]])

# Đường chéo chính của ma trận A
np.diag(A)

array([1, 5, 9])

In [55]:
print("Original matrix: \n", A)
print("Transpose matrix: \n", A.T)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [56]:
# Tính ma trận nghịch đảo của A
# pinv là pseudo-inverse of a matrix
A = np.array([[1, 2.5, 2],
              [3, 4.2, 1],
              [5, 2.1, 2]])

A_inv=np.linalg.pinv(A)

print("Inverse A: ")
A_inv

Inverse A: 


array([[-0.24609375,  0.03125   ,  0.23046875],
       [ 0.0390625 ,  0.3125    , -0.1953125 ],
       [ 0.57421875, -0.40625   ,  0.12890625]])

In [57]:
A.dot(A_inv)

array([[ 1.00000000e+00,  4.44089210e-16, -6.10622664e-16],
       [ 2.22044605e-16,  1.00000000e+00, -6.10622664e-16],
       [-2.22044605e-16, -4.44089210e-16,  1.00000000e+00]])

In [58]:
np.linalg.matrix_rank(A)

3

In [59]:
# Tính định thức của A
np.linalg.det(A)

-25.6

In [60]:
print("matrix A: \n", A)
print("trace of A: ", np.trace(A))

matrix A: 
 [[1.  2.5 2. ]
 [3.  4.2 1. ]
 [5.  2.1 2. ]]
trace of A:  7.2


In [61]:
np.linalg.norm(A, ord='fro')

8.502940667792526

In [62]:
import numpy as np
A = np.array([[1, 4, 2],
              [3, 2, 1],
              [4, 6, 7]])

B = np.array([[0, 3, 4],
              [3, 4, 2],
              [4, 6, 8]])

A - B

array([[ 1,  1, -2],
       [ 0, -2, -1],
       [ 0,  0, -1]])

In [63]:
import numpy as np
A = np.array([[1, 4, 2],
              [3, 2, 1]])

B = np.array([[0, 3],
              [3, 4],
              [4, 6]])

np.dot(A, B)
# Hoặc
A.dot(B)
# Hoặc
A@B

array([[20, 31],
       [10, 23]])

In [64]:
# Tích của hai ma trận A và B
C = np.array([[2, 1, 2],
              [1, 0, 1]])

D = np.array([[0, 2, 4],
              [2, 3, 1]])

C*D

array([[0, 2, 8],
       [2, 0, 1]])

In [65]:
x = np.array([1, 2, 3])
A.dot(x)

array([15, 10])

In [66]:
A*5

array([[ 5, 20, 10],
       [15, 10,  5]])

In [67]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 5])
# Phép cộng
a+b
# Tích vô hướng
a.dot(b)
# Tích có hướng
a*b
# cosine similarity
a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.954029957691665

In [68]:
# Hoặc cách khác để tính cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 5]])

cosine_similarity(a, b)

array([[0.95402996]])

In [69]:
print('shape: ', A.shape)
print('number dims: ', A.ndim)
print('dtype: ', A.dtype)
print('item bytes size: ', A.itemsize)
print('bytes size: ', A.nbytes)

shape:  (2, 3)
number dims:  2
dtype:  int64
item bytes size:  8
bytes size:  48


In [70]:
A.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [71]:
import numpy as np

A = np.array([[10, 1, 2],
              [9, 7, 4],
              [0, 2, 1]])

B = np.array([[2, 3, 4],
              [0, 4, 2],
              [3, 2, 1]])