In [1]:
import torch

a = torch.tensor(20)
b = torch.tensor(200)
print("diện tích x = 50 --> giá nhà y = a*50+b = ", a*50+b)

diện tích x = 50 --> giá nhà y = a*50+b =  tensor(1200)


In [2]:
x = torch.tensor([1, 1.2, 1.5, 1.8, 2])
x

tensor([1.0000, 1.2000, 1.5000, 1.8000, 2.0000])

In [3]:
# Độ dài
print("length of vector: ", x.size()) # or len(x)

# Định dạng của véc tơ
print("vector type: ", x.dtype)

# Tổng của các phần tử 
print("sum of vector: ", x.sum())

# Trung bình các phần tử
print("mean of vector: ", x.mean())

# Giá trị nhỏ nhất
print("min of vector: ", x.min())

# Giá trị lớn nhất
print("max of vector: ", x.max())

length of vector:  torch.Size([5])
vector type:  torch.float32
sum of vector:  tensor(7.5000)
mean of vector:  tensor(1.5000)
min of vector:  tensor(1.)
max of vector:  tensor(2.)


In [4]:
x = torch.tensor([1, 2, 1.5, 1.8, 1.9])
y = torch.tensor([1.1, 2.2, 1.2, 1.6, 1.7])
print("x + y: ", x + y)
print("x - y: ", x - y)
print("x * y: ", x * y)

x + y:  tensor([2.1000, 4.2000, 2.7000, 3.4000, 3.6000])
x - y:  tensor([-0.1000, -0.2000,  0.3000,  0.2000,  0.2000])
x * y:  tensor([1.1000, 4.4000, 1.8000, 2.8800, 3.2300])


In [5]:
x = torch.tensor([1, 2, 1.5, 1.8, 1.9])
print("x + 5: ", x + 5)
print("x - 5: ", x - 5)
print("x * 5: ", x * 5)

x + 5:  tensor([6.0000, 7.0000, 6.5000, 6.8000, 6.9000])
x - 5:  tensor([-4.0000, -3.0000, -3.5000, -3.2000, -3.1000])
x * 5:  tensor([ 5.0000, 10.0000,  7.5000,  9.0000,  9.5000])


In [6]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1]])

# shape của matrix A
A.size()

torch.Size([2, 3])

In [7]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1]])

B = torch.tensor([[2, 1, 2], 
                  [1, 3, 0]])

A*B

tensor([[2, 2, 6],
        [3, 6, 0]])

In [8]:
print("A-B: \n", A-B)
print("A+B: \n", A+B)

A-B: 
 tensor([[-1,  1,  1],
        [ 2, -1,  1]])
A+B: 
 tensor([[3, 3, 5],
        [4, 5, 1]])


In [9]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1]])

B = torch.tensor([[2, 1], 
                  [1, 3],
                  [1, 1]])

A@B

tensor([[ 7, 10],
        [ 9, 10]])

In [10]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1],
                  [4, 2, 2]])

# Truy cập ma trận con từ 2 dòng đầu tiên và 2 cột đầu tiên.
A[:2, :2]

tensor([[1, 2],
        [3, 2]])

In [11]:
# Truy cập ma trận con từ 2 dòng cuối cùng và 2 cột đầu tiên
A[-2:, :2]

tensor([[3, 2],
        [4, 2]])

In [12]:
# Truy cập véc tơ con từ dòng thứ 2 và 2 cột cuối cùng.
print(A[2, -2:])

# Hoặc
A[2:3, -2:][0]

tensor([2, 2])


tensor([2, 2])

In [13]:
# Truy cập ma trận có các dòng chẵn
A[::2, :]

tensor([[1, 2, 3],
        [4, 2, 2]])

In [14]:
# Truy cập một index cụ thể ví dụ dòng 0, 2 của ma trận
A.index_select(0, torch.tensor([0, 2]))
# Trong công thức trên 0 là chiều mà ta sẽ lấy, tensor([0, 2]) là các index ta sẽ lấy từ chiều 0.

tensor([[1, 2, 3],
        [4, 2, 2]])

In [15]:
A = torch.tensor([[[1, 2, 3], 
                  [3, 2, 1]],
                  [[2, 1, 2], 
                  [1, 3, 0]]])

# Kích thước của tensor
print("shape of A: " , A.size())

# Số chiều 
print("total dim: ", A.ndim)

# Định dạng dữ liệu
print("dtype: ", A.dtype)

shape of A:  torch.Size([2, 2, 3])
total dim:  3
dtype:  torch.int64


In [16]:
import torch

A = torch.randn([2, 3, 4])
B = torch.randn([2, 4, 2])

# Tích giữa 2 tensor
(A@B).size()

torch.Size([2, 3, 2])

In [17]:
import torch

A = torch.randn([2, 3, 4])
B = torch.randn([2, 3, 4])

# Tích hadamard giữa 2 tensor
(A*B).size()

torch.Size([2, 3, 4])

In [18]:
# Phép cộng
(A+B).size()

torch.Size([2, 3, 4])

In [19]:
# Phép trừ
(A-B).size()

torch.Size([2, 3, 4])

In [20]:
import torch

# Khởi tạo ma trận A kích thước m, n, p = 2, 3, 4
A = torch.randn([2, 3, 4])

# Truy cập ma trận đầu tiên 
A[:1, :, :]

tensor([[[-1.5483,  0.6321,  0.8363, -0.1253],
         [ 2.1015, -0.9334,  1.3284, -0.5874],
         [ 1.1368,  1.1072, -0.2711, -0.2864]]])

In [21]:
# Truy cập ma trận đầu tiên và chỉ lấy dòng từ 1 tới 3
A[0][1:3, :]

tensor([[ 2.1015, -0.9334,  1.3284, -0.5874],
        [ 1.1368,  1.1072, -0.2711, -0.2864]])

In [22]:
# Truy cập tương ứng với các chiều m, n, p lần lượt index đầu tiên, 2 index đầu tiên, và index thứ 3.
A[:1, :2, 3]

tensor([[-0.1253, -0.5874]])

In [23]:
import torch

X = torch.tensor([[100, 120, 80, 90, 105, 95], 
                  [2, 3, 2, 2, 3, 2]])

In [24]:
w = torch.tensor([[10], [100]])
y = X.T@w
y

tensor([[1200],
        [1500],
        [1000],
        [1100],
        [1350],
        [1150]])

In [25]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([2, 3, 4])
x.dot(y)

tensor(20)

In [26]:
import torch
x = torch.randn(10)
torch.norm(x, p=2)

tensor(2.5612)

In [27]:
print(torch.norm(x, p=1))
# hoặc 
torch.abs(x).sum()

tensor(5.5196)


tensor(5.5196)

In [28]:
# chuẩn p bất kỳ >= 1, chẳng hạn p=1.5
torch.norm(x, p=1.5)

tensor(3.2034)